// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: app/ratelimit/api/ratelimit.proto

package ratelimitpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetKeyModeRequest_Mode int32

const (
	SetKeyModeRequest_UUID   SetKeyModeRequest_Mode = 0
	SetKeyModeRequest_DEVICE SetKeyModeRequest_Mode = 1
)

// Enum value maps for SetKeyModeRequest_Mode.
var (
	SetKeyModeRequest_Mode_name = map[int32]string{
		0: "UUID",
		1: "DEVICE",
	}
	SetKeyModeRequest_Mode_value = map[string]int32{
		"UUID":   0,
		"DEVICE": 1,
	}
)

func (x SetKeyModeRequest_Mode) Enum() *SetKeyModeRequest_Mode {
	p := new(SetKeyModeRequest_Mode)
	*p = x
	return p
}

func (x SetKeyModeRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetKeyModeRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_app_ratelimit_api_ratelimit_proto_enumTypes[0].Descriptor()
}

func (SetKeyModeRequest_Mode) Type() protoreflect.EnumType {
	return &file_app_ratelimit_api_ratelimit_proto_enumTypes[0]
}

func (x SetKeyModeRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetKeyModeRequest_Mode.Descriptor instead.
func (SetKeyModeRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{6, 0}
}

type ClearUserEgressCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUserEgressCacheRequest) Reset() {
	*x = ClearUserEgressCacheRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUserEgressCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUserEgressCacheRequest) ProtoMessage() {}

func (x *ClearUserEgressCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUserEgressCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearUserEgressCacheRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *ClearUserEgressCacheRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ClearUserEgressCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cleared       uint32                 `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"` // сколько deviceEntry сбросили
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUserEgressCacheResponse) Reset() {
	*x = ClearUserEgressCacheResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUserEgressCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUserEgressCacheResponse) ProtoMessage() {}

func (x *ClearUserEgressCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUserEgressCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearUserEgressCacheResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *ClearUserEgressCacheResponse) GetCleared() uint32 {
	if x != nil {
		return x.Cleared
	}
	return 0
}

type SetGraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       uint32                 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGraceRequest) Reset() {
	*x = SetGraceRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGraceRequest) ProtoMessage() {}

func (x *SetGraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGraceRequest.ProtoReflect.Descriptor instead.
func (*SetGraceRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{2}
}

func (x *SetGraceRequest) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type SetGraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGraceResponse) Reset() {
	*x = SetGraceResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGraceResponse) ProtoMessage() {}

func (x *SetGraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGraceResponse.ProtoReflect.Descriptor instead.
func (*SetGraceResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{3}
}

type GetGraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraceRequest) Reset() {
	*x = GetGraceRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraceRequest) ProtoMessage() {}

func (x *GetGraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraceRequest.ProtoReflect.Descriptor instead.
func (*GetGraceRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{4}
}

type GetGraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       uint32                 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraceResponse) Reset() {
	*x = GetGraceResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraceResponse) ProtoMessage() {}

func (x *GetGraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraceResponse.ProtoReflect.Descriptor instead.
func (*GetGraceResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{5}
}

func (x *GetGraceResponse) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type SetKeyModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          SetKeyModeRequest_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=ratelimit.v1.SetKeyModeRequest_Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyModeRequest) Reset() {
	*x = SetKeyModeRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyModeRequest) ProtoMessage() {}

func (x *SetKeyModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyModeRequest.ProtoReflect.Descriptor instead.
func (*SetKeyModeRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{6}
}

func (x *SetKeyModeRequest) GetMode() SetKeyModeRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return SetKeyModeRequest_UUID
}

type SetKeyModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyModeResponse) Reset() {
	*x = SetKeyModeResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyModeResponse) ProtoMessage() {}

func (x *SetKeyModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyModeResponse.ProtoReflect.Descriptor instead.
func (*SetKeyModeResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{7}
}

type GetKeyModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyModeRequest) Reset() {
	*x = GetKeyModeRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyModeRequest) ProtoMessage() {}

func (x *GetKeyModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyModeRequest.ProtoReflect.Descriptor instead.
func (*GetKeyModeRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{8}
}

type GetKeyModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          SetKeyModeRequest_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=ratelimit.v1.SetKeyModeRequest_Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyModeResponse) Reset() {
	*x = GetKeyModeResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyModeResponse) ProtoMessage() {}

func (x *GetKeyModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyModeResponse.ProtoReflect.Descriptor instead.
func (*GetKeyModeResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{9}
}

func (x *GetKeyModeResponse) GetMode() SetKeyModeRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return SetKeyModeRequest_UUID
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserStatsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetUserStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DeviceCount      uint32                 `protobuf:"varint,2,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"`
	RxBytesTotal     uint64                 `protobuf:"varint,3,opt,name=rx_bytes_total,json=rxBytesTotal,proto3" json:"rx_bytes_total,omitempty"`
	TxBytesTotal     uint64                 `protobuf:"varint,4,opt,name=tx_bytes_total,json=txBytesTotal,proto3" json:"tx_bytes_total,omitempty"`
	StartedAtUnixMin uint64                 `protobuf:"varint,5,opt,name=started_at_unix_min,json=startedAtUnixMin,proto3" json:"started_at_unix_min,omitempty"` // самое раннее Started среди устройств
	LastSeenUnixMax  uint64                 `protobuf:"varint,6,opt,name=last_seen_unix_max,json=lastSeenUnixMax,proto3" json:"last_seen_unix_max,omitempty"`    // самое позднее LastSeen среди устройств
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserStatsResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetUserStatsResponse) GetDeviceCount() uint32 {
	if x != nil {
		return x.DeviceCount
	}
	return 0
}

func (x *GetUserStatsResponse) GetRxBytesTotal() uint64 {
	if x != nil {
		return x.RxBytesTotal
	}
	return 0
}

func (x *GetUserStatsResponse) GetTxBytesTotal() uint64 {
	if x != nil {
		return x.TxBytesTotal
	}
	return 0
}

func (x *GetUserStatsResponse) GetStartedAtUnixMin() uint64 {
	if x != nil {
		return x.StartedAtUnixMin
	}
	return 0
}

func (x *GetUserStatsResponse) GetLastSeenUnixMax() uint64 {
	if x != nil {
		return x.LastSeenUnixMax
	}
	return 0
}

type SetUserTotalLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DownBps       uint64                 `protobuf:"varint,2,opt,name=down_bps,json=downBps,proto3" json:"down_bps,omitempty"`
	UpBps         uint64                 `protobuf:"varint,3,opt,name=up_bps,json=upBps,proto3" json:"up_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserTotalLimitRequest) Reset() {
	*x = SetUserTotalLimitRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserTotalLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTotalLimitRequest) ProtoMessage() {}

func (x *SetUserTotalLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTotalLimitRequest.ProtoReflect.Descriptor instead.
func (*SetUserTotalLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserTotalLimitRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SetUserTotalLimitRequest) GetDownBps() uint64 {
	if x != nil {
		return x.DownBps
	}
	return 0
}

func (x *SetUserTotalLimitRequest) GetUpBps() uint64 {
	if x != nil {
		return x.UpBps
	}
	return 0
}

type SetUserTotalLimitResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceCount      uint32                 `protobuf:"varint,1,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"` // сколько устройств было найдено
	PerDeviceDownBps uint64                 `protobuf:"varint,2,opt,name=per_device_down_bps,json=perDeviceDownBps,proto3" json:"per_device_down_bps,omitempty"`
	PerDeviceUpBps   uint64                 `protobuf:"varint,3,opt,name=per_device_up_bps,json=perDeviceUpBps,proto3" json:"per_device_up_bps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetUserTotalLimitResponse) Reset() {
	*x = SetUserTotalLimitResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserTotalLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTotalLimitResponse) ProtoMessage() {}

func (x *SetUserTotalLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTotalLimitResponse.ProtoReflect.Descriptor instead.
func (*SetUserTotalLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserTotalLimitResponse) GetDeviceCount() uint32 {
	if x != nil {
		return x.DeviceCount
	}
	return 0
}

func (x *SetUserTotalLimitResponse) GetPerDeviceDownBps() uint64 {
	if x != nil {
		return x.PerDeviceDownBps
	}
	return 0
}

func (x *SetUserTotalLimitResponse) GetPerDeviceUpBps() uint64 {
	if x != nil {
		return x.PerDeviceUpBps
	}
	return 0
}

type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	StartedAtUnix uint64                 `protobuf:"varint,2,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	LastSeenUnix  uint64                 `protobuf:"varint,3,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{14}
}

func (x *ConnectionInfo) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *ConnectionInfo) GetStartedAtUnix() uint64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *ConnectionInfo) GetLastSeenUnix() uint64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *ConnectionInfo) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *ConnectionInfo) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

type SetUserDefaultPerConnLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DownBps       uint64                 `protobuf:"varint,2,opt,name=down_bps,json=downBps,proto3" json:"down_bps,omitempty"`
	UpBps         uint64                 `protobuf:"varint,3,opt,name=up_bps,json=upBps,proto3" json:"up_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDefaultPerConnLimitRequest) Reset() {
	*x = SetUserDefaultPerConnLimitRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDefaultPerConnLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDefaultPerConnLimitRequest) ProtoMessage() {}

func (x *SetUserDefaultPerConnLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDefaultPerConnLimitRequest.ProtoReflect.Descriptor instead.
func (*SetUserDefaultPerConnLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{15}
}

func (x *SetUserDefaultPerConnLimitRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SetUserDefaultPerConnLimitRequest) GetDownBps() uint64 {
	if x != nil {
		return x.DownBps
	}
	return 0
}

func (x *SetUserDefaultPerConnLimitRequest) GetUpBps() uint64 {
	if x != nil {
		return x.UpBps
	}
	return 0
}

type SetUserDefaultPerConnLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDefaultPerConnLimitResponse) Reset() {
	*x = SetUserDefaultPerConnLimitResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDefaultPerConnLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDefaultPerConnLimitResponse) ProtoMessage() {}

func (x *SetUserDefaultPerConnLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDefaultPerConnLimitResponse.ProtoReflect.Descriptor instead.
func (*SetUserDefaultPerConnLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{16}
}

type ListUserConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserConnectionsRequest) Reset() {
	*x = ListUserConnectionsRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserConnectionsRequest) ProtoMessage() {}

func (x *ListUserConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserConnectionsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ListUserConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*ConnectionInfo      `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserConnectionsResponse) Reset() {
	*x = ListUserConnectionsResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserConnectionsResponse) ProtoMessage() {}

func (x *ListUserConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{18}
}

func (x *ListUserConnectionsResponse) GetConnections() []*ConnectionInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

type SetConnectionLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	DownBps       uint64                 `protobuf:"varint,2,opt,name=down_bps,json=downBps,proto3" json:"down_bps,omitempty"`
	UpBps         uint64                 `protobuf:"varint,3,opt,name=up_bps,json=upBps,proto3" json:"up_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectionLimitRequest) Reset() {
	*x = SetConnectionLimitRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionLimitRequest) ProtoMessage() {}

func (x *SetConnectionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionLimitRequest.ProtoReflect.Descriptor instead.
func (*SetConnectionLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{19}
}

func (x *SetConnectionLimitRequest) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *SetConnectionLimitRequest) GetDownBps() uint64 {
	if x != nil {
		return x.DownBps
	}
	return 0
}

func (x *SetConnectionLimitRequest) GetUpBps() uint64 {
	if x != nil {
		return x.UpBps
	}
	return 0
}

type SetConnectionLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectionLimitResponse) Reset() {
	*x = SetConnectionLimitResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionLimitResponse) ProtoMessage() {}

func (x *SetConnectionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionLimitResponse.ProtoReflect.Descriptor instead.
func (*SetConnectionLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{20}
}

type ClearConnectionLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearConnectionLimitRequest) Reset() {
	*x = ClearConnectionLimitRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearConnectionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearConnectionLimitRequest) ProtoMessage() {}

func (x *ClearConnectionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearConnectionLimitRequest.ProtoReflect.Descriptor instead.
func (*ClearConnectionLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{21}
}

func (x *ClearConnectionLimitRequest) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type ClearConnectionLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearConnectionLimitResponse) Reset() {
	*x = ClearConnectionLimitResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearConnectionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearConnectionLimitResponse) ProtoMessage() {}

func (x *ClearConnectionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearConnectionLimitResponse.ProtoReflect.Descriptor instead.
func (*ClearConnectionLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{22}
}

type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// IP адрес, который сервер видит как Source IP клиента (без порта)
	SrcIp string `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	// Уникальный ключ "устройства" на сервере: uuid + "|" + src_ip
	DeviceKey string `protobuf:"bytes,3,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	// Внутренний ConnID, к которому привязан лимитер (может меняться между рестартами)
	ConnId uint64 `protobuf:"varint,4,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// Сколько inbound TCP соединений сейчас у этого устройства (refcount)
	RefCount uint32 `protobuf:"varint,5,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	// Момент, когда устройство было создано (первый старт) и последнее событие
	StartedAtUnix uint64 `protobuf:"varint,6,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	LastSeenUnix  uint64 `protobuf:"varint,7,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	// Статистика трафика
	RxBytes       uint64 `protobuf:"varint,8,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64 `protobuf:"varint,9,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{23}
}

func (x *DeviceInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeviceInfo) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *DeviceInfo) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *DeviceInfo) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *DeviceInfo) GetRefCount() uint32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *DeviceInfo) GetStartedAtUnix() uint64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *DeviceInfo) GetLastSeenUnix() uint64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *DeviceInfo) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *DeviceInfo) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

type GetActiveDevicesSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveDevicesSnapshotRequest) Reset() {
	*x = GetActiveDevicesSnapshotRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveDevicesSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveDevicesSnapshotRequest) ProtoMessage() {}

func (x *GetActiveDevicesSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveDevicesSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetActiveDevicesSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{24}
}

type GetActiveDevicesSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveDevicesSnapshotResponse) Reset() {
	*x = GetActiveDevicesSnapshotResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveDevicesSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveDevicesSnapshotResponse) ProtoMessage() {}

func (x *GetActiveDevicesSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveDevicesSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetActiveDevicesSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{25}
}

func (x *GetActiveDevicesSnapshotResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListUserDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDevicesRequest) Reset() {
	*x = ListUserDevicesRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDevicesRequest) ProtoMessage() {}

func (x *ListUserDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListUserDevicesRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{26}
}

func (x *ListUserDevicesRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ListUserDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDevicesResponse) Reset() {
	*x = ListUserDevicesResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDevicesResponse) ProtoMessage() {}

func (x *ListUserDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListUserDevicesResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{27}
}

func (x *ListUserDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SetDeviceLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceKey     string                 `protobuf:"bytes,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	DownBps       uint64                 `protobuf:"varint,2,opt,name=down_bps,json=downBps,proto3" json:"down_bps,omitempty"`
	UpBps         uint64                 `protobuf:"varint,3,opt,name=up_bps,json=upBps,proto3" json:"up_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceLimitRequest) Reset() {
	*x = SetDeviceLimitRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceLimitRequest) ProtoMessage() {}

func (x *SetDeviceLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceLimitRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{28}
}

func (x *SetDeviceLimitRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *SetDeviceLimitRequest) GetDownBps() uint64 {
	if x != nil {
		return x.DownBps
	}
	return 0
}

func (x *SetDeviceLimitRequest) GetUpBps() uint64 {
	if x != nil {
		return x.UpBps
	}
	return 0
}

type SetDeviceLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceLimitResponse) Reset() {
	*x = SetDeviceLimitResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceLimitResponse) ProtoMessage() {}

func (x *SetDeviceLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceLimitResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{29}
}

type ClearDeviceLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceKey     string                 `protobuf:"bytes,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDeviceLimitRequest) Reset() {
	*x = ClearDeviceLimitRequest{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDeviceLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDeviceLimitRequest) ProtoMessage() {}

func (x *ClearDeviceLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDeviceLimitRequest.ProtoReflect.Descriptor instead.
func (*ClearDeviceLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{30}
}

func (x *ClearDeviceLimitRequest) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

type ClearDeviceLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDeviceLimitResponse) Reset() {
	*x = ClearDeviceLimitResponse{}
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDeviceLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDeviceLimitResponse) ProtoMessage() {}

func (x *ClearDeviceLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_ratelimit_api_ratelimit_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDeviceLimitResponse.ProtoReflect.Descriptor instead.
func (*ClearDeviceLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_ratelimit_api_ratelimit_proto_rawDescGZIP(), []int{31}
}

var File_app_ratelimit_api_ratelimit_proto protoreflect.FileDescriptor

const file_app_ratelimit_api_ratelimit_proto_rawDesc = "" +
	"\n" +
	"!app/ratelimit/api/ratelimit.proto\x12\fratelimit.v1\"1\n" +
	"\x1bClearUserEgressCacheRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"8\n" +
	"\x1cClearUserEgressCacheResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\rR\acleared\"+\n" +
	"\x0fSetGraceRequest\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\rR\aseconds\"\x12\n" +
	"\x10SetGraceResponse\"\x11\n" +
	"\x0fGetGraceRequest\",\n" +
	"\x10GetGraceResponse\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\rR\aseconds\"k\n" +
	"\x11SetKeyModeRequest\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.ratelimit.v1.SetKeyModeRequest.ModeR\x04mode\"\x1c\n" +
	"\x04Mode\x12\b\n" +
	"\x04UUID\x10\x00\x12\n" +
	"\n" +
	"\x06DEVICE\x10\x01\"\x14\n" +
	"\x12SetKeyModeResponse\"\x13\n" +
	"\x11GetKeyModeRequest\"N\n" +
	"\x12GetKeyModeResponse\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.ratelimit.v1.SetKeyModeRequest.ModeR\x04mode\")\n" +
	"\x13GetUserStatsRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xf5\x01\n" +
	"\x14GetUserStatsResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fdevice_count\x18\x02 \x01(\rR\vdeviceCount\x12$\n" +
	"\x0erx_bytes_total\x18\x03 \x01(\x04R\frxBytesTotal\x12$\n" +
	"\x0etx_bytes_total\x18\x04 \x01(\x04R\ftxBytesTotal\x12-\n" +
	"\x13started_at_unix_min\x18\x05 \x01(\x04R\x10startedAtUnixMin\x12+\n" +
	"\x12last_seen_unix_max\x18\x06 \x01(\x04R\x0flastSeenUnixMax\"`\n" +
	"\x18SetUserTotalLimitRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x19\n" +
	"\bdown_bps\x18\x02 \x01(\x04R\adownBps\x12\x15\n" +
	"\x06up_bps\x18\x03 \x01(\x04R\x05upBps\"\x98\x01\n" +
	"\x19SetUserTotalLimitResponse\x12!\n" +
	"\fdevice_count\x18\x01 \x01(\rR\vdeviceCount\x12-\n" +
	"\x13per_device_down_bps\x18\x02 \x01(\x04R\x10perDeviceDownBps\x12)\n" +
	"\x11per_device_up_bps\x18\x03 \x01(\x04R\x0eperDeviceUpBps\"\xad\x01\n" +
	"\x0eConnectionInfo\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\x12&\n" +
	"\x0fstarted_at_unix\x18\x02 \x01(\x04R\rstartedAtUnix\x12$\n" +
	"\x0elast_seen_unix\x18\x03 \x01(\x04R\flastSeenUnix\x12\x19\n" +
	"\brx_bytes\x18\x04 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x04R\atxBytes\"i\n" +
	"!SetUserDefaultPerConnLimitRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x19\n" +
	"\bdown_bps\x18\x02 \x01(\x04R\adownBps\x12\x15\n" +
	"\x06up_bps\x18\x03 \x01(\x04R\x05upBps\"$\n" +
	"\"SetUserDefaultPerConnLimitResponse\"0\n" +
	"\x1aListUserConnectionsRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"]\n" +
	"\x1bListUserConnectionsResponse\x12>\n" +
	"\vconnections\x18\x01 \x03(\v2\x1c.ratelimit.v1.ConnectionInfoR\vconnections\"f\n" +
	"\x19SetConnectionLimitRequest\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\x12\x19\n" +
	"\bdown_bps\x18\x02 \x01(\x04R\adownBps\x12\x15\n" +
	"\x06up_bps\x18\x03 \x01(\x04R\x05upBps\"\x1c\n" +
	"\x1aSetConnectionLimitResponse\"6\n" +
	"\x1bClearConnectionLimitRequest\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x04R\x06connId\"\x1e\n" +
	"\x1cClearConnectionLimitResponse\"\x90\x02\n" +
	"\n" +
	"DeviceInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x1d\n" +
	"\n" +
	"device_key\x18\x03 \x01(\tR\tdeviceKey\x12\x17\n" +
	"\aconn_id\x18\x04 \x01(\x04R\x06connId\x12\x1b\n" +
	"\tref_count\x18\x05 \x01(\rR\brefCount\x12&\n" +
	"\x0fstarted_at_unix\x18\x06 \x01(\x04R\rstartedAtUnix\x12$\n" +
	"\x0elast_seen_unix\x18\a \x01(\x04R\flastSeenUnix\x12\x19\n" +
	"\brx_bytes\x18\b \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\t \x01(\x04R\atxBytes\"!\n" +
	"\x1fGetActiveDevicesSnapshotRequest\"V\n" +
	" GetActiveDevicesSnapshotResponse\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.ratelimit.v1.DeviceInfoR\adevices\",\n" +
	"\x16ListUserDevicesRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"M\n" +
	"\x17ListUserDevicesResponse\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.ratelimit.v1.DeviceInfoR\adevices\"h\n" +
	"\x15SetDeviceLimitRequest\x12\x1d\n" +
	"\n" +
	"device_key\x18\x01 \x01(\tR\tdeviceKey\x12\x19\n" +
	"\bdown_bps\x18\x02 \x01(\x04R\adownBps\x12\x15\n" +
	"\x06up_bps\x18\x03 \x01(\x04R\x05upBps\"\x18\n" +
	"\x16SetDeviceLimitResponse\"8\n" +
	"\x17ClearDeviceLimitRequest\x12\x1d\n" +
	"\n" +
	"device_key\x18\x01 \x01(\tR\tdeviceKey\"\x1a\n" +
	"\x18ClearDeviceLimitResponse2\xd6\v\n" +
	"\x10RateLimitService\x12\x7f\n" +
	"\x1aSetUserDefaultPerConnLimit\x12/.ratelimit.v1.SetUserDefaultPerConnLimitRequest\x1a0.ratelimit.v1.SetUserDefaultPerConnLimitResponse\x12j\n" +
	"\x13ListUserConnections\x12(.ratelimit.v1.ListUserConnectionsRequest\x1a).ratelimit.v1.ListUserConnectionsResponse\x12g\n" +
	"\x12SetConnectionLimit\x12'.ratelimit.v1.SetConnectionLimitRequest\x1a(.ratelimit.v1.SetConnectionLimitResponse\x12m\n" +
	"\x14ClearConnectionLimit\x12).ratelimit.v1.ClearConnectionLimitRequest\x1a*.ratelimit.v1.ClearConnectionLimitResponse\x12y\n" +
	"\x18GetActiveDevicesSnapshot\x12-.ratelimit.v1.GetActiveDevicesSnapshotRequest\x1a..ratelimit.v1.GetActiveDevicesSnapshotResponse\x12^\n" +
	"\x0fListUserDevices\x12$.ratelimit.v1.ListUserDevicesRequest\x1a%.ratelimit.v1.ListUserDevicesResponse\x12[\n" +
	"\x0eSetDeviceLimit\x12#.ratelimit.v1.SetDeviceLimitRequest\x1a$.ratelimit.v1.SetDeviceLimitResponse\x12a\n" +
	"\x10ClearDeviceLimit\x12%.ratelimit.v1.ClearDeviceLimitRequest\x1a&.ratelimit.v1.ClearDeviceLimitResponse\x12d\n" +
	"\x11SetUserTotalLimit\x12&.ratelimit.v1.SetUserTotalLimitRequest\x1a'.ratelimit.v1.SetUserTotalLimitResponse\x12U\n" +
	"\fGetUserStats\x12!.ratelimit.v1.GetUserStatsRequest\x1a\".ratelimit.v1.GetUserStatsResponse\x12O\n" +
	"\n" +
	"SetKeyMode\x12\x1f.ratelimit.v1.SetKeyModeRequest\x1a .ratelimit.v1.SetKeyModeResponse\x12O\n" +
	"\n" +
	"GetKeyMode\x12\x1f.ratelimit.v1.GetKeyModeRequest\x1a .ratelimit.v1.GetKeyModeResponse\x12I\n" +
	"\bSetGrace\x12\x1d.ratelimit.v1.SetGraceRequest\x1a\x1e.ratelimit.v1.SetGraceResponse\x12I\n" +
	"\bGetGrace\x12\x1d.ratelimit.v1.GetGraceRequest\x1a\x1e.ratelimit.v1.GetGraceResponse\x12m\n" +
	"\x14ClearUserEgressCache\x12).ratelimit.v1.ClearUserEgressCacheRequest\x1a*.ratelimit.v1.ClearUserEgressCacheResponseB9Z7github.com/xtls/xray-core/app/ratelimit/api;ratelimitpbb\x06proto3"

var (
	file_app_ratelimit_api_ratelimit_proto_rawDescOnce sync.Once
	file_app_ratelimit_api_ratelimit_proto_rawDescData []byte
)

func file_app_ratelimit_api_ratelimit_proto_rawDescGZIP() []byte {
	file_app_ratelimit_api_ratelimit_proto_rawDescOnce.Do(func() {
		file_app_ratelimit_api_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_ratelimit_api_ratelimit_proto_rawDesc), len(file_app_ratelimit_api_ratelimit_proto_rawDesc)))
	})
	return file_app_ratelimit_api_ratelimit_proto_rawDescData
}

var file_app_ratelimit_api_ratelimit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_ratelimit_api_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_app_ratelimit_api_ratelimit_proto_goTypes = []any{
	(SetKeyModeRequest_Mode)(0),                // 0: ratelimit.v1.SetKeyModeRequest.Mode
	(*ClearUserEgressCacheRequest)(nil),        // 1: ratelimit.v1.ClearUserEgressCacheRequest
	(*ClearUserEgressCacheResponse)(nil),       // 2: ratelimit.v1.ClearUserEgressCacheResponse
	(*SetGraceRequest)(nil),                    // 3: ratelimit.v1.SetGraceRequest
	(*SetGraceResponse)(nil),                   // 4: ratelimit.v1.SetGraceResponse
	(*GetGraceRequest)(nil),                    // 5: ratelimit.v1.GetGraceRequest
	(*GetGraceResponse)(nil),                   // 6: ratelimit.v1.GetGraceResponse
	(*SetKeyModeRequest)(nil),                  // 7: ratelimit.v1.SetKeyModeRequest
	(*SetKeyModeResponse)(nil),                 // 8: ratelimit.v1.SetKeyModeResponse
	(*GetKeyModeRequest)(nil),                  // 9: ratelimit.v1.GetKeyModeRequest
	(*GetKeyModeResponse)(nil),                 // 10: ratelimit.v1.GetKeyModeResponse
	(*GetUserStatsRequest)(nil),                // 11: ratelimit.v1.GetUserStatsRequest
	(*GetUserStatsResponse)(nil),               // 12: ratelimit.v1.GetUserStatsResponse
	(*SetUserTotalLimitRequest)(nil),           // 13: ratelimit.v1.SetUserTotalLimitRequest
	(*SetUserTotalLimitResponse)(nil),          // 14: ratelimit.v1.SetUserTotalLimitResponse
	(*ConnectionInfo)(nil),                     // 15: ratelimit.v1.ConnectionInfo
	(*SetUserDefaultPerConnLimitRequest)(nil),  // 16: ratelimit.v1.SetUserDefaultPerConnLimitRequest
	(*SetUserDefaultPerConnLimitResponse)(nil), // 17: ratelimit.v1.SetUserDefaultPerConnLimitResponse
	(*ListUserConnectionsRequest)(nil),         // 18: ratelimit.v1.ListUserConnectionsRequest
	(*ListUserConnectionsResponse)(nil),        // 19: ratelimit.v1.ListUserConnectionsResponse
	(*SetConnectionLimitRequest)(nil),          // 20: ratelimit.v1.SetConnectionLimitRequest
	(*SetConnectionLimitResponse)(nil),         // 21: ratelimit.v1.SetConnectionLimitResponse
	(*ClearConnectionLimitRequest)(nil),        // 22: ratelimit.v1.ClearConnectionLimitRequest
	(*ClearConnectionLimitResponse)(nil),       // 23: ratelimit.v1.ClearConnectionLimitResponse
	(*DeviceInfo)(nil),                         // 24: ratelimit.v1.DeviceInfo
	(*GetActiveDevicesSnapshotRequest)(nil),    // 25: ratelimit.v1.GetActiveDevicesSnapshotRequest
	(*GetActiveDevicesSnapshotResponse)(nil),   // 26: ratelimit.v1.GetActiveDevicesSnapshotResponse
	(*ListUserDevicesRequest)(nil),             // 27: ratelimit.v1.ListUserDevicesRequest
	(*ListUserDevicesResponse)(nil),            // 28: ratelimit.v1.ListUserDevicesResponse
	(*SetDeviceLimitRequest)(nil),              // 29: ratelimit.v1.SetDeviceLimitRequest
	(*SetDeviceLimitResponse)(nil),             // 30: ratelimit.v1.SetDeviceLimitResponse
	(*ClearDeviceLimitRequest)(nil),            // 31: ratelimit.v1.ClearDeviceLimitRequest
	(*ClearDeviceLimitResponse)(nil),           // 32: ratelimit.v1.ClearDeviceLimitResponse
}
var file_app_ratelimit_api_ratelimit_proto_depIdxs = []int32{
	0,  // 0: ratelimit.v1.SetKeyModeRequest.mode:type_name -> ratelimit.v1.SetKeyModeRequest.Mode
	0,  // 1: ratelimit.v1.GetKeyModeResponse.mode:type_name -> ratelimit.v1.SetKeyModeRequest.Mode
	15, // 2: ratelimit.v1.ListUserConnectionsResponse.connections:type_name -> ratelimit.v1.ConnectionInfo
	24, // 3: ratelimit.v1.GetActiveDevicesSnapshotResponse.devices:type_name -> ratelimit.v1.DeviceInfo
	24, // 4: ratelimit.v1.ListUserDevicesResponse.devices:type_name -> ratelimit.v1.DeviceInfo
	16, // 5: ratelimit.v1.RateLimitService.SetUserDefaultPerConnLimit:input_type -> ratelimit.v1.SetUserDefaultPerConnLimitRequest
	18, // 6: ratelimit.v1.RateLimitService.ListUserConnections:input_type -> ratelimit.v1.ListUserConnectionsRequest
	20, // 7: ratelimit.v1.RateLimitService.SetConnectionLimit:input_type -> ratelimit.v1.SetConnectionLimitRequest
	22, // 8: ratelimit.v1.RateLimitService.ClearConnectionLimit:input_type -> ratelimit.v1.ClearConnectionLimitRequest
	25, // 9: ratelimit.v1.RateLimitService.GetActiveDevicesSnapshot:input_type -> ratelimit.v1.GetActiveDevicesSnapshotRequest
	27, // 10: ratelimit.v1.RateLimitService.ListUserDevices:input_type -> ratelimit.v1.ListUserDevicesRequest
	29, // 11: ratelimit.v1.RateLimitService.SetDeviceLimit:input_type -> ratelimit.v1.SetDeviceLimitRequest
	31, // 12: ratelimit.v1.RateLimitService.ClearDeviceLimit:input_type -> ratelimit.v1.ClearDeviceLimitRequest
	13, // 13: ratelimit.v1.RateLimitService.SetUserTotalLimit:input_type -> ratelimit.v1.SetUserTotalLimitRequest
	11, // 14: ratelimit.v1.RateLimitService.GetUserStats:input_type -> ratelimit.v1.GetUserStatsRequest
	7,  // 15: ratelimit.v1.RateLimitService.SetKeyMode:input_type -> ratelimit.v1.SetKeyModeRequest
	9,  // 16: ratelimit.v1.RateLimitService.GetKeyMode:input_type -> ratelimit.v1.GetKeyModeRequest
	3,  // 17: ratelimit.v1.RateLimitService.SetGrace:input_type -> ratelimit.v1.SetGraceRequest
	5,  // 18: ratelimit.v1.RateLimitService.GetGrace:input_type -> ratelimit.v1.GetGraceRequest
	1,  // 19: ratelimit.v1.RateLimitService.ClearUserEgressCache:input_type -> ratelimit.v1.ClearUserEgressCacheRequest
	17, // 20: ratelimit.v1.RateLimitService.SetUserDefaultPerConnLimit:output_type -> ratelimit.v1.SetUserDefaultPerConnLimitResponse
	19, // 21: ratelimit.v1.RateLimitService.ListUserConnections:output_type -> ratelimit.v1.ListUserConnectionsResponse
	21, // 22: ratelimit.v1.RateLimitService.SetConnectionLimit:output_type -> ratelimit.v1.SetConnectionLimitResponse
	23, // 23: ratelimit.v1.RateLimitService.ClearConnectionLimit:output_type -> ratelimit.v1.ClearConnectionLimitResponse
	26, // 24: ratelimit.v1.RateLimitService.GetActiveDevicesSnapshot:output_type -> ratelimit.v1.GetActiveDevicesSnapshotResponse
	28, // 25: ratelimit.v1.RateLimitService.ListUserDevices:output_type -> ratelimit.v1.ListUserDevicesResponse
	30, // 26: ratelimit.v1.RateLimitService.SetDeviceLimit:output_type -> ratelimit.v1.SetDeviceLimitResponse
	32, // 27: ratelimit.v1.RateLimitService.ClearDeviceLimit:output_type -> ratelimit.v1.ClearDeviceLimitResponse
	14, // 28: ratelimit.v1.RateLimitService.SetUserTotalLimit:output_type -> ratelimit.v1.SetUserTotalLimitResponse
	12, // 29: ratelimit.v1.RateLimitService.GetUserStats:output_type -> ratelimit.v1.GetUserStatsResponse
	8,  // 30: ratelimit.v1.RateLimitService.SetKeyMode:output_type -> ratelimit.v1.SetKeyModeResponse
	10, // 31: ratelimit.v1.RateLimitService.GetKeyMode:output_type -> ratelimit.v1.GetKeyModeResponse
	4,  // 32: ratelimit.v1.RateLimitService.SetGrace:output_type -> ratelimit.v1.SetGraceResponse
	6,  // 33: ratelimit.v1.RateLimitService.GetGrace:output_type -> ratelimit.v1.GetGraceResponse
	2,  // 34: ratelimit.v1.RateLimitService.ClearUserEgressCache:output_type -> ratelimit.v1.ClearUserEgressCacheResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_app_ratelimit_api_ratelimit_proto_init() }
func file_app_ratelimit_api_ratelimit_proto_init() {
	if File_app_ratelimit_api_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_ratelimit_api_ratelimit_proto_rawDesc), len(file_app_ratelimit_api_ratelimit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_ratelimit_api_ratelimit_proto_goTypes,
		DependencyIndexes: file_app_ratelimit_api_ratelimit_proto_depIdxs,
		EnumInfos:         file_app_ratelimit_api_ratelimit_proto_enumTypes,
		MessageInfos:      file_app_ratelimit_api_ratelimit_proto_msgTypes,
	}.Build()
	File_app_ratelimit_api_ratelimit_proto = out.File
	file_app_ratelimit_api_ratelimit_proto_goTypes = nil
	file_app_ratelimit_api_ratelimit_proto_depIdxs = nil
}
